name: Atualizar Data JSON

on:
  workflow_dispatch:
    inputs:
      content:
        description: 'Conteúdo JSON para atualizar data.json'
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar data.json
        run: |
                printf "%s" '${{ github.event.inputs.content }}' > data.json

      - name: Commit e push das alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git commit -m "Atualizar data.json via workflow"
          git push
